#!/usr/bin/env python2

from testlib import *

r = Runner()

def matchtest(parent, name, points, *args, **kw):
    def do_test():
        r.match(*args, **kw)
    test(points, name, parent=parent)(do_test)

@test(0, "part2 [part2.c]")
def test_part2():
    r.run_test("build/part2")
matchtest(test_part2, "part2", 20, "part2: OK")

run_tests()
