#!/usr/bin/env python2

from testlib import *

r = Runner()

def matchtest(parent, name, points, *args, **kw):
    def do_test():
        r.match(*args, **kw)
    test(points, name, parent=parent)(do_test)

@test(0, "[part4.c]")
def test_part4():
    r.run_test("build/part4")
matchtest(test_part4, "part4", 20, "part4: OK")

run_tests()
