#!/usr/bin/env python2

from testlib import *

r = Runner()

def matchtest(parent, name, points, *args, **kw):
    def do_test():
        r.match(*args, **kw)
    test(points, name, parent=parent)(do_test)

@test(0, "part1 [part1.c]")
def test_part1():
    r.run_test("build/part1")
matchtest(test_part1, "part1", 10, "part1: OK")

run_tests()
