#!/usr/bin/env python2

from testlib import *

r = Runner()

def matchtest(parent, name, points, *args, **kw):
    def do_test():
        r.match(*args, **kw)
    test(points, name, parent=parent)(do_test)

@test(0, "[part3.c]")
def test_part3():
    r.run_test("build/part3")
matchtest(test_part3, "part3", 20, "part3: OK")

run_tests()
